### ISSUE TITLE
CameraRoll.saveToCameraRoll doesn't save images to phone gallery

### ISSUE THREAD

**Issue by kiransawant15** [react-native-cameraroll/react-native-cameraroll#164]
When i run following code photo doesn't get saved in gallery all the permissions are set in androidmanifest.xml file

The following code prints promise rejected in console please help

takePicture = async () => {

if (this.camera) {
  const options = { quality: 0.5, base64: true };
  const data = await this.camera.takePictureAsync(options);
  console.log(data.uri);
  console.log(CameraRoll.getAlbums);
  CameraRoll.saveToCameraRoll(data.uri,"photo").catch(function () {
  console.log("Promise Rejected");
  });

}
}

**Comment by kiransawant15** [comment]
Further if i i dont catch the promise and make it like below

**Comment by wibes** [comment]
getting same issue. Please help

**Comment by huyhai** [comment]
same

**Comment by TuJobs** [comment]
Update version 1.5.2 , working with me!

**Comment by wibes** [comment]
I just updated still not working for me getting same issue. On some devices its working but not working on "Redmi" devices

**Comment by Lunziyuan** [comment]
same

**Comment by wibes** [comment]
Any update ?

**Comment by cmakhija** [comment]
Any update facing same issues on Redmi phones

**Comment by dokkis** [comment]
might be related to https://github.com/react-native-community/react-native-cameraroll/pull/94 and https://github.com/react-native-community/react-native-cameraroll/issues/141.

Can anybody check if changing the library to use DCIM would fix the issue?

**Comment by bartolkaruza** [comment]
https://github.com/react-native-community/react-native-cameraroll/issues/141 has just been released in version 1.7.2

We suspect this issue may be resolved through that change, but I don't have a way to test on the specific devices that the issue occurs on. Can someone confirm if version 1.7.2 fixes this issue? @wibes

**Comment by sfseyhan** [comment]
I am getting the same error on UI tests I run on multiple android devices on AWS device farm, where devices don't have any media. So if you're looking for ways to reproduce it, you can use a public aws device-farm device. I've seen the error in following devices
Google Pixel 4 (Unlocked)  API 10
Samsung Galaxy Note 10  API 9
Samsung Galaxy S9+ (Unlocked) API 8.0.0

When I manually access to the device via remote access, take a photo with device camera, saveToCameraRoll starts working again.

I guess if there is no media on a device it's not guaranteed to have a media directory? Or device farm might be deleting any default directories on session start, that would otherwise exist in stock android devices.

I'm using 1.7.1, haven't tried 1.7.2
