### ISSUE TITLE
Support Android Scoped Storage

### ISSUE THREAD

**Issue by nicoburns** [react-native-cameraroll/react-native-cameraroll#244]
It is currently necessary to add `android:requestLegacyExternalStorage="true"` to make images picked by the library work correctly on Android 10 (see #219). As documented [here](https://developer.android.com/about/versions/11/privacy/storage), that option will be going away in Android API level 30 (Android 11), by which point this plugin will need to have implemented the new scoped storage APIs in order to continue functioning.

**Comment by bartolkaruza** [comment]
#242 Happy to take PR's for this

**Comment by lon9man** [comment]
@bartolkaruza or somebody
### **DOCS**
Starting in August 2021, new apps will need to:
...
- Target API level 30 (Android 11) ...

...
Starting in November 2021, app updates will be required to target API level 30.
information from here: https://developer.android.com/distribute/best-practices/develop/target-sdk

### **PRE-HISTORY**
1. i ran your example-app with `targetSdkVersion 30` on emulator
![image](https://user-images.githubusercontent.com/10497794/114006684-529de680-9869-11eb-88af-f2a18e3bb818.png)
2. it works as expected (**BUT** i also see that it uses deprecated MediaStore's `DATA`-column, so it uses raw paths, which AFAIU won't work in Android 11 as announced by Google): 
    a) it shows thumbnails
    b) JSON-response from method `getPhotos`
    i tried such paths like:
```
    /storage/emulated/0/Pictures
    /storage/emulated/0/PicturesX
    /storage/emulated/0/DCIM/Pictures
    /storage/emulated/0/DCIM/Pictures/PicturesX
    /storage/emulated/0/Movies
    /storage/emulated/0/Downloads
    /storage/emulated/0/Downloads/ABC
    ...
```

can you answer on the next questions, because i have read tons of docs/forums and sadly still don't have clear understanding:
1. why your example still works in Android 11 emulator?
2. `cameraRoll` currently makes 2 major things: 
    a) queries MediaStore to get all images/videos from **WHOLE** storage 
        WHAT will change here on Android 11? 
        will it can return the same results (_like all paths above_) for **WHOLE** storage (_not only scoped storage_)?

    b) returns **uri** `file://...` to React Native to render thumbnail (using `raw` paths as i see in sources) 
        WHAT will change here on Android 11? 
        how React Native will can render thumbnails if `raw` paths will not be available due to deprecating `DATA`-column in MediaStore. what is the alternative possible?

**Comment by mars-lan** [comment]
Looks like the deadline is May not August

```
Starting May 5th, you must let us know why your app requires broad storage access

We've detected that your app contains the requestLegacyExternalStorage flag in the manifest file of 1 or more of your app bundles or APKs.

Developers with apps on devices running Android 11+ must use Scoped Storage to give users better access control over their device storage. To release your app on Android 11 or newer after May 5th, you must either:

- Update your app to use more privacy friendly best practices, such as the Storage Access Framework or Media Store API
- Update your app to declare the All files access (MANAGE_EXTERNAL_STORAGE) permission in the manifest file, and complete the All files access permission declaration in Play Console from May 5th
- Remove the All files access permission from your app entirely
For apps targeting Android 11, the requestLegacyExternalStorage flag will be ignored. You must use the All files access permission to retain broad access.

Apps requesting access to the All files access permission without a permitted use will be removed from Google Play, and you won't be able to publish updates.
```

**Comment by mars-lan** [comment]
Nvm, looks like there's traction in https://github.com/react-native-cameraroll/react-native-cameraroll/issues/304
