### ISSUE TITLE
[Android] [Samsung Galaxy] Rotated image always shows up as landscape

### ISSUE THREAD

**Issue by mmmulani** [react-native-cameraroll/react-native-cameraroll#33]
When using `CameraRoll.getPhotos` for a photo taken in portrait mode on a Galaxy S9, you get a larger width than height (i.e. a landscape photo). From searching around, it seems like this is a known issue: https://stackoverflow.com/questions/47261434/photo-rotated-from-camera-samsung-device but can be solved by looking at the EXIF data.

**Comment by bartolkaruza** [comment]
Hi and thank you for reporting! There appears to be some uncertainty about the accepted answer solving all device/os version combinations. What version of Android are you running on your S9? Are you able to reproduce this consistently?

**Comment by mmmulani** [comment]
oh actually it's happening on a Samsung S8, model number: SM-G950U. I'm relaying the bug report for a colleague, so I'll try to find out what version of Android they're using

**Comment by zlorenzini** [comment]
I have the same issue on a Galaxy Note 9 with Android Pie. I am getting the width as 4302 and height as 1960, but the issue only occurs with actual photos taken by the camera. Screenshots and downloads are not affected.

**Comment by Ashoat** [comment]
I've had similar issues with older Android devices where the dimensions are crossed, specifically for videos. I've tried:

1. Sourcing dimensions from this package (`@react-native-community/cameraroll`), didn't work
2. Sourcing dimensions from `expo-media-library`, didn't work
3. Sourcing dimensions from EXIF data via `react-native-exif` and `react-native-ffmpeg`, didn't work (which suggests perhaps this is a different issue than the OP)
4. Sourcing dimensions from `Image.getSize`. In this case the scale was off by the ratio was correct
5. Sourcing dimensions from `react-native-video`. This works, but only when using the older MediaPlayer implementation (as opposed to the newer ExoPlayer one, due to https://github.com/react-native-community/react-native-video/issues/1530)
