### ISSUE TITLE
publish to npm

### ISSUE THREAD

**Issue by jbrodriguez** [react-native-cameraroll/react-native-cameraroll#410]
hi, glad to see the new version released !!

@idrissakhi could you please publish it to npm ?

**Comment by idrissakhi** [comment]
Waiting for @bartolkaruza to grant me authorization

**Comment by bartolkaruza** [comment]
@idrissakhi can you reach out to me on Twitter DM, @bartolkaruza
I'll show you how to do things.

**Comment by bartolkaruza** [comment]
Also please let me know your twitter username here, to close the loop 😄

**Comment by bartolkaruza** [comment]
I'm going to try to fix the release mechanism. Please don't make manual releases, they mess with sementic-release

**Comment by idrissakhi** [comment]
hey @bartolkaruza, this is my twitter username: @sakhi_idris i will send you a message right away. we can close this thread and i will try to clean the issues board later

**Comment by Arjan-Zuidema** [comment]
My twitter is @arjanzuidema I you could message me too would be awesome 🙂

**Comment by bartolkaruza** [comment]
@Arjan-Zuidema your DM's are not open? Drop me a message so we can connect. 

You guys are awesome

**Comment by bartolkaruza** [comment]
Also to clarify, we're fixing some issues with the release process, new release should be out soon

**Comment by santhoshvai** [comment]
Hi @bartolkaruza thank you for taking this up again and giving opportunity for other maintainers. Could you please give us an ETA on a new release? I am working on a [SDK](https://github.com/GetStream/stream-chat-react-native) that has cameraroll as a peer dependency and over the last year due to non availability of Android 11 support I had create a [fork](https://github.com/GetStream/react-native-cameraroll). We are currently recommending our users to use the fork in our next major release but we would love to drop it and use the original instead.

**Comment by bartolkaruza** [comment]
@santhoshvai I'm hoping to resolve this today

**Comment by bartolkaruza** [comment]
It's actually done now! Make sure to read the readme, the package name is changed!

**Comment by bartolkaruza** [comment]
https://github.com/react-native-cameraroll/react-native-cameraroll/releases/tag/v5.0.0

**Comment by santhoshvai** [comment]
Thanks a lot @bartolkaruza
