### ISSUE TITLE
Cannot save .SVG images to camera roll

### ISSUE THREAD

**Issue by gmferraz** [react-native-cameraroll/react-native-cameraroll#432]
Cannot save .svg images for both iOS and Android currently. 

Received this error message when tried to download to my device. 
`Error: The operation couldn’t be completed. (PHPhotosErrorDomain error 3303.)`

**Comment by Hashir524** [comment]
I can't save a video same error is poppping up. any Solution?

**Comment by gmferraz** [comment]
@Hashir524 nothing yet :(

**Comment by go-sean-go** [comment]
Had the same problem myself, but found a fix related to a few related problems (I could not share an SVG to the system `Share()` sheet, for example).

The fix is to prepend some metadata, like this: `data:image/png;base64,${base64ImageString}`. In general, I need to do this anytime I want to work with the base64 SVG as I would with a 'typical' image.

So the full implementation would be like:
```
await CameraRoll.save(
  `data:image/png;base64,${base64ImageString.current}`,
);
```

Hope this helps!
